spring:
  config.activate.on-profile: prod
  main.web-application-type: none
  batch:
    job:
      enabled: true
      name: ${job.name:NONE}

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml