feign-clients:
  producthunt:
    mode: rest
    uri: https://api.producthunt.com/v2
    token: ${PRODUCTHUNT_TOKEN:}

---
spring:
  config.activate.on-profile: test
feign-clients:
  producthunt:
    mode: mock
    uri: https://api.producthunt.com/v2
    token: ${PRODUCTHUNT_TOKEN:}

---
spring:
  config.activate.on-profile: local, dev
  cloud:
    openfeign:
      client:
        config:
          ProductHuntFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  producthunt:
    mode: rest
    uri: ${PRODUCTHUNT_FEIGN_URI:https://api.producthunt.com/v2}
    token: ${PRODUCTHUNT_TOKEN:}

---
spring:
  config.activate.on-profile: beta
  cloud:
    openfeign:
      client:
        config:
          ProductHuntFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  producthunt:
    mode: rest
    uri: ${PRODUCTHUNT_FEIGN_URI:https://api.producthunt.com/v2}
    token: ${PRODUCTHUNT_TOKEN:}


---
spring:
  config.activate.on-profile: prod
  cloud:
    openfeign:
      client:
        okhttp:
          enabled: true
        httpclient:
          max-connections: 35000
          max-connections-per-route: 35000
          connection-timeout: 120000 # 120초
          hc5:
            connection-request-timeout: 120000 # 120초
            socket-timeout: 120000 # 120초
        config:
          ProductHuntFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  producthunt:
    mode: rest
    uri: ${PRODUCTHUNT_FEIGN_URI:https://api.producthunt.com/v2}
    token: ${PRODUCTHUNT_TOKEN:}
