feign-clients:
  hackernews:
    mode: rest
    uri: https://hacker-news.firebaseio.com/v0

---
spring:
  config.activate.on-profile: test
feign-clients:
  hackernews:
    mode: mock
    uri: https://hacker-news.firebaseio.com/v0

---
spring:
  config.activate.on-profile: local, dev
  cloud:
    openfeign:
      client:
        config:
          HackerNewsFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  hackernews:
    mode: rest
    uri: ${HACKER_NEWS_FEIGN_URI:https://hacker-news.firebaseio.com/v0}

---
spring:
  config.activate.on-profile: beta
  cloud:
    openfeign:
      client:
        config:
          HackerNewsFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  hackernews:
    mode: rest
    uri: ${HACKER_NEWS_FEIGN_URI:https://hacker-news.firebaseio.com/v0}


---
spring:
  config.activate.on-profile: prod
  cloud:
    openfeign:
      client:
        okhttp:
          enabled: true
        httpclient:
          max-connections: 35000
          max-connections-per-route: 35000
          connection-timeout: 120000 # 120초
          hc5:
            connection-request-timeout: 120000 # 120초
            socket-timeout: 120000 # 120초
        config:
          HackerNewsFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  hackernews:
    mode: rest
    uri: ${HACKER_NEWS_FEIGN_URI:https://hacker-news.firebaseio.com/v0}
