feign-clients:
  devto:
    mode: rest
    uri: https://dev.to/api
    api-key: ${DEVTO_API_KEY:}

---
spring:
  config.activate.on-profile: test
feign-clients:
  devto:
    mode: mock
    uri: https://dev.to/api
    api-key: ${DEVTO_API_KEY:}

---
spring:
  config.activate.on-profile: local, dev
  cloud:
    openfeign:
      client:
        config:
          DevToFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  devto:
    mode: rest
    uri: ${DEVTO_FEIGN_URI:https://dev.to/api}
    api-key: ${DEVTO_API_KEY:}

---
spring:
  config.activate.on-profile: beta
  cloud:
    openfeign:
      client:
        config:
          DevToFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  devto:
    mode: rest
    uri: ${DEVTO_FEIGN_URI:https://dev.to/api}
    api-key: ${DEVTO_API_KEY:}


---
spring:
  config.activate.on-profile: prod
  cloud:
    openfeign:
      client:
        okhttp:
          enabled: true
        httpclient:
          max-connections: 35000
          max-connections-per-route: 35000
          connection-timeout: 120000 # 120초
          hc5:
            connection-request-timeout: 120000 # 120초
            socket-timeout: 120000 # 120초
        config:
          DevToFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  devto:
    mode: rest
    uri: ${DEVTO_FEIGN_URI:https://dev.to/api}
    api-key: ${DEVTO_API_KEY:}
