feign-clients:
  kaggle:
    mode: rest
    uri: https://www.kaggle.com/api/v1
    api-key: ${KAGGLE_API_KEY:}

---
spring:
  config.activate.on-profile: test
feign-clients:
  kaggle:
    mode: mock
    uri: https://www.kaggle.com/api/v1
    api-key: ${KAGGLE_API_KEY:}

---
spring:
  config.activate.on-profile: local, dev
  cloud:
    openfeign:
      client:
        config:
          KaggleFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  kaggle:
    mode: rest
    uri: ${KAGGLE_FEIGN_URI:https://www.kaggle.com/api/v1}
    api-key: ${KAGGLE_API_KEY:}

---
spring:
  config.activate.on-profile: beta
  cloud:
    openfeign:
      client:
        config:
          KaggleFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  kaggle:
    mode: rest
    uri: ${KAGGLE_FEIGN_URI:https://www.kaggle.com/api/v1}
    api-key: ${KAGGLE_API_KEY:}


---
spring:
  config.activate.on-profile: prod
  cloud:
    openfeign:
      client:
        okhttp:
          enabled: true
        httpclient:
          max-connections: 35000
          max-connections-per-route: 35000
          connection-timeout: 120000 # 120초
          hc5:
            connection-request-timeout: 120000 # 120초
            socket-timeout: 120000 # 120초
        config:
          KaggleFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  kaggle:
    mode: rest
    uri: ${KAGGLE_FEIGN_URI:https://www.kaggle.com/api/v1}
    api-key: ${KAGGLE_API_KEY:}
