feign-clients:
  reddit:
    mode: rest
    uri: https://www.reddit.com
    token: ${REDDIT_TOKEN:}

---
spring:
  config.activate.on-profile: test
feign-clients:
  reddit:
    mode: mock
    uri: https://www.reddit.com
    token: ${REDDIT_TOKEN:}

---
spring:
  config.activate.on-profile: local, dev
  cloud:
    openfeign:
      client:
        config:
          RedditFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  reddit:
    mode: rest
    uri: ${REDDIT_FEIGN_URI:https://www.reddit.com}
    token: ${REDDIT_TOKEN:}

---
spring:
  config.activate.on-profile: beta
  cloud:
    openfeign:
      client:
        config:
          RedditFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  reddit:
    mode: rest
    uri: ${REDDIT_FEIGN_URI:https://www.reddit.com}
    token: ${REDDIT_TOKEN:}


---
spring:
  config.activate.on-profile: prod
  cloud:
    openfeign:
      client:
        okhttp:
          enabled: true
        httpclient:
          max-connections: 35000
          max-connections-per-route: 35000
          connection-timeout: 120000 # 120초
          hc5:
            connection-request-timeout: 120000 # 120초
            socket-timeout: 120000 # 120초
        config:
          RedditFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  reddit:
    mode: rest
    uri: ${REDDIT_FEIGN_URI:https://www.reddit.com}
    token: ${REDDIT_TOKEN:}
