feign-clients:
  codeforces:
    mode: rest
    uri: https://codeforces.com

---
spring:
  config.activate.on-profile: test
feign-clients:
  codeforces:
    mode: mock
    uri: https://codeforces.com

---
spring:
  config.activate.on-profile: local, dev
  cloud:
    openfeign:
      client:
        config:
          CodeforcesFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  codeforces:
    mode: rest
    uri: ${CODEFORCES_FEIGN_URI:https://codeforces.com}

---
spring:
  config.activate.on-profile: beta
  cloud:
    openfeign:
      client:
        config:
          CodeforcesFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  codeforces:
    mode: rest
    uri: ${CODEFORCES_FEIGN_URI:https://codeforces.com}


---
spring:
  config.activate.on-profile: prod
  cloud:
    openfeign:
      client:
        okhttp:
          enabled: true
        httpclient:
          max-connections: 35000
          max-connections-per-route: 35000
          connection-timeout: 120000 # 120초
          hc5:
            connection-request-timeout: 120000 # 120초
            socket-timeout: 120000 # 120초
        config:
          CodeforcesFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  codeforces:
    mode: rest
    uri: ${CODEFORCES_FEIGN_URI:https://codeforces.com}
