feign-clients:
  sample:
    mode: rest
    uri: http://localhost:8080

---
spring:
  config.activate.on-profile: test
feign-clients:
  sample:
    mode: mock
    uri: http://localhost:8080

---
spring:
  config.activate.on-profile: local, dev
  cloud:
    openfeign:
      client:
        config:
          SampleFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  sample:
    mode: rest
    uri: ${SAMPLE_FEIGN_URI}

---
spring:
  config.activate.on-profile: beta
  cloud:
    openfeign:
      client:
        config:
          SampleFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  sample:
    mode: rest
    uri: ${SAMPLE_FEIGN_URI}


---
spring:
  config.activate.on-profile: prod
  cloud:
    openfeign:
      client:
        okhttp:
          enabled: true
        httpclient:
          max-connections: 35000
          max-connections-per-route: 35000
          connection-timeout: 120000 # 120초
          hc5:
            connection-request-timeout: 120000 # 120초
            socket-timeout: 120000 # 120초
        config:
          SampleFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  sample:
    mode: rest
    uri: ${SAMPLE_FEIGN_URI}

