feign-clients:
  newsapi:
    mode: rest
    uri: https://newsapi.org/v2
    api-key: ${NEWSAPI_API_KEY:}

---
spring:
  config.activate.on-profile: test
feign-clients:
  newsapi:
    mode: mock
    uri: https://newsapi.org/v2
    api-key: ${NEWSAPI_API_KEY:}

---
spring:
  config.activate.on-profile: local, dev
  cloud:
    openfeign:
      client:
        config:
          NewsAPIFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  newsapi:
    mode: rest
    uri: ${NEWSAPI_FEIGN_URI:https://newsapi.org/v2}
    api-key: ${NEWSAPI_API_KEY:}

---
spring:
  config.activate.on-profile: beta
  cloud:
    openfeign:
      client:
        config:
          NewsAPIFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  newsapi:
    mode: rest
    uri: ${NEWSAPI_FEIGN_URI:https://newsapi.org/v2}
    api-key: ${NEWSAPI_API_KEY:}


---
spring:
  config.activate.on-profile: prod
  cloud:
    openfeign:
      client:
        okhttp:
          enabled: true
        httpclient:
          max-connections: 35000
          max-connections-per-route: 35000
          connection-timeout: 120000 # 120초
          hc5:
            connection-request-timeout: 120000 # 120초
            socket-timeout: 120000 # 120초
        config:
          NewsAPIFeign:
            readTimeout: 30000
            connectTimeout: 3000

feign-clients:
  newsapi:
    mode: rest
    uri: ${NEWSAPI_FEIGN_URI:https://newsapi.org/v2}
    api-key: ${NEWSAPI_API_KEY:}
