spring:
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:ebson024.v1@gmail.com}
    password: ${MAIL_PASSWORD:rdxzemhatprwllck}
    properties:
      mail.smtp.auth: ${MAIL_SMTP_AUTH:true}
      mail.smtp.starttls.enable: ${MAIL_SMTP_STARTTLS:true}
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 3000
      mail.smtp.writetimeout: 5000

mail:
  from-address: ${MAIL_FROM_ADDRESS:ebson024.v1@gmail.com}
  from-name: Shrimp TM (Local)
  base-url: http://localhost:3000
