server:
  port: 8087

spring:
  application:
    name: agent-api
  profiles:
    include:
      - common-core
      - agent-api
      - feign-github
      - feign-internal
      - slack
      - scraper
